FORMAT: 1A

# PNPD API

Sprint 1
- PNPD-14,Log in with e-mail [User]
- PNPD-13,Log in with Facebook [User]
- PNPD-12,Signup with e-mail [User]
- PNPD-10,Signup with Facebook [User]
- PNPD-16,Send e-mail link to reset password [User]
- PNPD-60,Display activities in customize activity,[Customize My Painai]
- PNPD-65,Follow activities,[Customize My Painai]
- PNPD-63,Display continents in customize places,[Customize My Painai]
- PNPD-59,Display places by the continent,[Customize My Painai]
- PNPD-21,Filter Painai page [Feed]
- PNPD-72,Display continent in Explore page [Explore]

## Group Signup

#### Signup with e-mail [GET /v1/signup]


+ Parameters


+ Response 200

    An array of products
    
    + Body
    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "product_id": {
                    "type": "string",
                    "description": "Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles."
                  },
                  "description": {
                    "type": "string",
                    "description": "Description of product."
                  },
                  "display_name": {
                    "type": "string",
                    "description": "Display name of product."
                  },
                  "capacity": {
                    "type": "string",
                    "description": "Capacity of product. For example, 4 people."
                  },
                  "image": {
                    "type": "string",
                    "description": "Image URL representing the product."
                  }
                }
              }
            }

## Group Login