FORMAT: 1A
HOST: http://pnpd.qa.maqe.com/api/v1

# PNPD API

### Sprint 1
- PNPD-14,Log in with e-mail [User]
- PNPD-13,Log in with Facebook [User]
- PNPD-12,Signup with e-mail [User]
- PNPD-10,Signup with Facebook [User]
- PNPD-16,Send e-mail link to reset password [User]
- PNPD-60,Display activities in customize activity,[Customize My Painai]
- PNPD-65,Follow activities,[Customize My Painai]
- PNPD-63,Display continents in customize places,[Customize My Painai]
- PNPD-59,Display places by the continent,[Customize My Painai]
- PNPD-21,Filter Painai page [Feed]
- PNPD-72,Display continent in Explore page [Explore]

### Sprint 2

- PNPD-35,Assign location for share photo [Content Sharing]
- PNPD-36,Post content with comment activity and location [Content Sharing]
- PNPD-33,Take photo from camera [Content Sharing]
- PNPD-79,Preview content photo [Content Sharing]


## Group API Authentication and User login API
- PNPD-13,Log in with Facebook
- PNPD-14,Log in with e-mail

http://docs.pnpdauthen.apiary.io

## Access Token [/api/v1/login]

+ Attributes 
    + grant_type:password (string)
    + client_id:xxxx (string)
    + client_secret:xxxx (string)
    + username: test@gmail.com (string) - Email address , For login with facebook use "facebook" as username
    + password: pass (string) - User's password, For facebook login put a token
    
### Login with email and password or use facebook token [POST]
  
+ Request Get new token (application/x-www-form-urlencoded)

    + Body
    
            grant_type=password&client_id=xxx&client_secret=xxx&username=test@gmail.com&password=pass
    
+ Response 200
    
        {"access_token":"fy11wUpboz1UDUONtw6uOOk8yQSCkHIGP1pQ8pNo","token_type":"Bearer","expires_in":31536000,"refresh_token":"K4QysikD2oSIoFXS0IQulLNHb7IEL3Mhs75e4zjN"}


+ Request Get token with facebook login (application/x-www-form-urlencoded)

    + Body
    
            grant_type=password&client_id=xxx&client_secret=xxx&username=facebook&password=EAAYz6xSRxeABADX6hBiAmTfk2XWWjR3FUZBmlr3cZAbt4FMCafyTFkZB5uClPFU9GxlZAsjGYkTu2FcSwwAF75IJFYFCP5PpAeZAiPwHzpgflzahpgqSJnDCsiYsKZAJrNge1DjlaZB1MoXpMi1naxaZBwPZBDGXpacAZD
            
+ Response 200

        {"access_token":"fy11wUpboz1UDUONtw6uOOk8yQSCkHIGP1pQ8pNo","token_type":"Bearer","expires_in":31536000,"refresh_token":"K4QysikD2oSIoFXS0IQulLNHb7IEL3Mhs75e4zjN"}
        

## Refresh a Token [/oauth/access_token]

### Refresh token [POST]

+ Request Refresh token (application/x-www-form-urlencoded)
            
    + Body
    
            grant_type=refresh_token&client_id=xxx&client_secret=xxx&refresh_token=K4QysikD2oSIoFXS0IQulLNHb7IEL3Mhs75e4zjN

+ Response 200
        
        {"access_token":"E4gTfBdEM31og4IEBB7Cm3O3o9t2OcOgmF5Z1xCz","token_type":"Bearer","expires_in":3600,"refresh_token":"LYkeqVao2iorrbVSzoqsVenOwAjPxvONiS2P6l6O"}




## Group Signup

#### Signup with e-mail [POST /signup]
- PNPD-12,Signup with e-mail

+ Request (application/json)

        {
            "grant_type": "password",
            "client_id": "client",
            "client_secret":"pass",
            "username":"test@gmail.com",
            "password":"",
            "profile":{
                "display_name":"234234",
                "first_name":"John",
                "last_name":"Doe",
                "taglines":"Hi",
                "gender":"male",
                "date_of_birth":"1981-02-21"
            }
        }
        
+ Response 200 (application/json)

        {
          "access_token": "MwX87MfxIiLDvetjhnNO9VgGmfVhG3uJMXaLjblH",
          "token_type": "Bearer",
          "expires_in": 31536000,
          "refresh_token": "2HWUj41pXk85vnYopEX6cJgF3OYc0S4wl2JWnSMl"
        }

#### Signup with Facebook [POST /signup-facebook]
- PNPD-10,Signup with Facebook
+ Request with success (application/json)

        {
            "grant_type": "password",
            "client_id": "xxx",
            "client_secret":"xxx",
            "username":"facebook",
            "password":"EAAYz6xSRxeABADX6hBiAmTfk2XWWjR3FUZBmlr3cZAbt4FMCafyTFkZB5uClPFU9GxlZAsjGYkTu2FcSwwAF75IJFYFCP5PpAeZAiPwHzpgflzahpgqSJnDCsiYsKZAJrNge1DjlaZB1MoXpMi1naxaZBwPZBDGXpacAZD"
        }

+ Response 200 (application/json)

        {
          "access_token": "MwX87MfxIiLDvetjhnNO9VgGmfVhG3uJMXaLjblH",
          "token_type": "Bearer",
          "expires_in": 31536000,
          "refresh_token": "2HWUj41pXk85vnYopEX6cJgF3OYc0S4wl2JWnSMl"
        }
        
## Group Reset password
#### Send link to e-mail [POST /reset_password]
- PNPD-16,Send e-mail link to reset password
+ Request with success (application/json)

        {
            "email":"test@gmail.com"
        }


+ Response 200 (application/json)

        {
            "messages":["Success"]
        }
        
+ Request with error (application/json)

        {
            "email":"invalid@gmail.com"
        }

+ Response 200 (application/json)

        {
            "errors":["That email address is not valid. Please check it and try again"]
        }

## Group User Info
#### Current user [GET /me]

+ Request (application/json)
+ Response 200 (application/json)


        {"id":1,"email":"test@gmail.com","created_at":null,"updated_at":null}
        
+ Request With authentication fail (application/json)
+ Response 401 (application/json)

        {
          "message": "Failed to authenticate because of bad credentials or an invalid authorization header.",
          "status_code": 401
        }

## Group Customize My Painai
- PNPD-65, Follow activities
- PNPD-63, Display continents in customize places
- PNPD-59, Display places by the continent

### Follow [/follows]

#### Get all follow list [GET]
+ Request follow a activity with success (application/json)
+ Response 200 (application/json)

        {
            "places":[
                {
                    "id": 1,
                    "type": "countries",
                    "name": "England",
                },
                {
                    "id": 2,
                    "type": "city",
                    "name": "Madrid",
                },
                {
                    "id": 3,
                    "type": "city",
                    "name": "Madrid",
                },
                {
                    "id": 4,
                    "type": "city",
                    "name": "Rome",
                }
           ],
           "activities":[
                {
                    "id": 1,
                    "type": "activities",
                    "name": "PAI EAT",
                }
           ]
        }


#### Follow a activity or continent [POST]
+ Request follow a activity with success (application/json)

        [{"type":"activities","name":"PAI EAT"}]
        
+ Response 200 (application/json)

        {
            "messages":["Success"]
        }

+ Request Follow a continent with success (application/json)

        [{"type":"continents","name":"EUROPE"}]
        
+ Response 200 (application/json)

        {
            "messages":["Success"]
        }
        
        
#### Unfollow a activity or continent [DELETE]
+ Request unfollow a activity with success (application/json)

        [
            {
                "type": "activities",
                "name: "PAI EAT"
            }
        ]
        
+ Response 200 (application/json)

        {
            "messages":["Success"]
        }


### Activities [/activities]

#### List all activities [GET]

+ Request (application/json)
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "type": "activities",
            "name": "PAI EAT",
            "images": [
              "http://loremflickr.com/1000/1000/food/all"
            ],
            "endpoint": "/api/v1/activities/1"
          },
          {
            "id": 2,
            "type": "activities",
            "name": "PAI DRINK",
            "images": [
              "http://loremflickr.com/1000/1000/drink,beverage"
            ],
            "endpoint": "/api/v1/activities/2"
          },
          {
            "id": 3,
            "type": "activities",
            "name": "PAI SHOP",
            "images": [
              "http://loremflickr.com/1000/1000/shopping"
            ],
            "endpoint": "/api/v1/activities/3"
          },
          {
            "id": 4,
            "type": "activities",
            "name": "PAI SLEEP",
            "images": [
              "http://loremflickr.com/1000/1000/hotel,room/all"
            ],
            "endpoint": "/api/v1/activities/4"
          },
          {
            "id": 5,
            "type": "activities",
            "name": "PAI CHECK-IN",
            "images": [
              "http://loremflickr.com/1000/1000/landmark"
            ],
            "endpoint": "/api/v1/activities/5"
          },
          {
            "id": 6,
            "type": "activities",
            "name": "PAI ADVENTURE",
            "images": [
              "http://loremflickr.com/1000/1000/adventure"
            ],
            "endpoint": "/api/v1/activities/6"
          },
          {
            "id": 7,
            "type": "activities",
            "name": "PAI NATURE",
            "images": [
              "http://loremflickr.com/1000/1000/nature"
            ],
            "endpoint": "/api/v1/activities/7"
          },
          {
            "id": 8,
            "type": "activities",
            "name": "PAI SPORT",
            "images": [
              "http://loremflickr.com/1000/1000/sport"
            ],
            "endpoint": "/api/v1/activities/8"
          }
        ]


### Places [/places]

#### Display customize places [GET]
+ Request (application/json)
+ Response 200 (application/json)

        {
          "data": [
            {
              "id": 1,
              "type": "continents",
              "name": "EUROPE",
              "images": [
                "http://loremflickr.com/1000/1000/europe,landmark/all"
              ],
              "location": {
                "latitude": -86.290039,
                "longitude": 43.788452
              },
              "endpoint": "/api/v1/continents/1/countries"
            },
            {
              "id": 2,
              "type": "continents",
              "name": "AFRICA",
              "images": [
                "http://loremflickr.com/1000/1000/africa,landmark/all"
              ],
              "location": {
                "latitude": -71.197869,
                "longitude": 73.279322
              },
              "endpoint": "/api/v1/continents/2/countries"
            },
            {
              "id": 3,
              "type": "continents",
              "name": "NORTH AMERICA",
              "images": [
                "http://loremflickr.com/1000/1000/north%20america,landmark/all"
              ],
              "location": {
                "latitude": -4.571319,
                "longitude": 101.87816
              },
              "endpoint": "/api/v1/continents/3/countries"
            },
            {
              "id": 4,
              "type": "countries",
              "name": "THAILAND",
              "images": [
                "http://loremflickr.com/1000/1000/thailand,landmark/all"
              ],
              "location": {
                "latitude": 22.540198,
                "longitude": -75.055181
              },
              "endpoint": "/api/v1/countries/4/cities"
            },
            {
              "id": 5,
              "type": "continents",
              "name": "ASIA",
              "images": [
                "http://loremflickr.com/1000/1000/asia,landmark/all"
              ],
              "location": {
                "latitude": 70.258306,
                "longitude": -163.375881
              },
              "endpoint": "/api/v1/continents/5/countries"
            },
            {
              "id": 6,
              "type": "continents",
              "name": "SOUTH AMERICA",
              "images": [
                "http://loremflickr.com/1000/1000/south%20america,landmark/all"
              ],
              "location": {
                "latitude": -15.106235,
                "longitude": -174.590537
              },
              "endpoint": "/api/v1/continents/6/countries"
            },
            {
              "id": 7,
              "type": "continents",
              "name": "AUSTRALIA",
              "images": [
                "http://loremflickr.com/1000/1000/australia,landmark/all"
              ],
              "location": {
                "latitude": 53.766375,
                "longitude": -76.414729
              },
              "endpoint": "/api/v1/continents/7/countries"
            },
            {
              "id": 8,
              "type": "continents",
              "name": "ANTARCTICA",
              "images": [
                "http://loremflickr.com/1000/1000/antarctica/all"
              ],
              "location": {
                "latitude": -68.931063,
                "longitude": -123.010064
              },
              "endpoint": "/api/v1/continents/8/countries"
            }
          ],
          "meta": {
            "pagination": {
              "total": 8,
              "count": 8,
              "per_page": 8,
              "current_page": 1,
              "total_pages": 1,
              "links": []
            }
          }
        }
        

#### Display countries by the continent [GET /continents/{continent}/countries]

+ Parameters 
    + continent:1 (number)
    
+ Request (application/json)
+ Response 200 (application/json)

        {
          "data": [
            {
              "id": 1,
              "type": "countries",
              "name": "Austria",
              "images": [
                "http://loremflickr.com/1000/1000/austria,landmark/all"
              ],
              "location": {
                "latitude": 43.794576,
                "longitude": -80.668672
              },
              "endpoint": "/api/v1/countries/1/cities"
            },
            {
              "id": 2,
              "type": "countries",
              "name": "Belgium",
              "images": [
                "http://loremflickr.com/1000/1000/belgium,landmark/all"
              ],
              "location": {
                "latitude": 72.831701,
                "longitude": 78.296773
              },
              "endpoint": "/api/v1/countries/2/cities"
            },
            {
              "id": 3,
              "type": "countries",
              "name": "Bulgaria",
              "images": [
                "http://loremflickr.com/1000/1000/bulgaria,landmark/all"
              ],
              "location": {
                "latitude": 36.770766,
                "longitude": 59.481854
              },
              "endpoint": "/api/v1/countries/3/cities"
            },
            {
              "id": 4,
              "type": "countries",
              "name": "Croatia",
              "images": [
                "http://loremflickr.com/1000/1000/croatia,landmark/all"
              ],
              "location": {
                "latitude": 30.164212,
                "longitude": -69.334854
              },
              "endpoint": "/api/v1/countries/4/cities"
            },
            {
              "id": 5,
              "type": "countries",
              "name": "Cyprus",
              "images": [
                "http://loremflickr.com/1000/1000/cyprus,landmark/all"
              ],
              "location": {
                "latitude": 71.649051,
                "longitude": 122.50274
              },
              "endpoint": "/api/v1/countries/5/cities"
            },
            {
              "id": 6,
              "type": "countries",
              "name": "Czech Republic",
              "images": [
                "http://loremflickr.com/1000/1000/czech%20republic,landmark/all"
              ],
              "location": {
                "latitude": -88.714599,
                "longitude": 40.864851
              },
              "endpoint": "/api/v1/countries/6/cities"
            },
            {
              "id": 7,
              "type": "countries",
              "name": "Denmark",
              "images": [
                "http://loremflickr.com/1000/1000/denmark,landmark/all"
              ],
              "location": {
                "latitude": 26.29359,
                "longitude": -24.627123
              },
              "endpoint": "/api/v1/countries/7/cities"
            },
            {
              "id": 8,
              "type": "countries",
              "name": "Estonia",
              "images": [
                "http://loremflickr.com/1000/1000/estonia,landmark/all"
              ],
              "location": {
                "latitude": -67.68033,
                "longitude": -58.385215
              },
              "endpoint": "/api/v1/countries/8/cities"
            },
            {
              "id": 9,
              "type": "countries",
              "name": "Finland",
              "images": [
                "http://loremflickr.com/1000/1000/finland,landmark/all"
              ],
              "location": {
                "latitude": -12.583973,
                "longitude": -5.07845
              },
              "endpoint": "/api/v1/countries/9/cities"
            },
            {
              "id": 10,
              "type": "countries",
              "name": "France",
              "images": [
                "http://loremflickr.com/1000/1000/france,landmark/all"
              ],
              "location": {
                "latitude": 86.589643,
                "longitude": -19.551743
              },
              "endpoint": "/api/v1/countries/10/cities"
            },
            {
              "id": 11,
              "type": "countries",
              "name": "Germany",
              "images": [
                "http://loremflickr.com/1000/1000/germany,landmark/all"
              ],
              "location": {
                "latitude": -21.347468,
                "longitude": 117.611705
              },
              "endpoint": "/api/v1/countries/11/cities"
            },
            {
              "id": 12,
              "type": "countries",
              "name": "Greece",
              "images": [
                "http://loremflickr.com/1000/1000/greece,landmark/all"
              ],
              "location": {
                "latitude": 79.015028,
                "longitude": -158.382461
              },
              "endpoint": "/api/v1/countries/12/cities"
            },
            {
              "id": 13,
              "type": "countries",
              "name": "Hungary",
              "images": [
                "http://loremflickr.com/1000/1000/hungary,landmark/all"
              ],
              "location": {
                "latitude": -52.586155,
                "longitude": 111.776513
              },
              "endpoint": "/api/v1/countries/13/cities"
            },
            {
              "id": 14,
              "type": "countries",
              "name": "Ireland",
              "images": [
                "http://loremflickr.com/1000/1000/ireland,landmark/all"
              ],
              "location": {
                "latitude": -72.848193,
                "longitude": 10.889473
              },
              "endpoint": "/api/v1/countries/14/cities"
            },
            {
              "id": 15,
              "type": "countries",
              "name": "Italy",
              "images": [
                "http://loremflickr.com/1000/1000/italy,landmark/all"
              ],
              "location": {
                "latitude": -9.011405,
                "longitude": 39.199439
              },
              "endpoint": "/api/v1/countries/15/cities"
            },
            {
              "id": 16,
              "type": "countries",
              "name": "Latvia",
              "images": [
                "http://loremflickr.com/1000/1000/latvia,landmark/all"
              ],
              "location": {
                "latitude": 9.393018,
                "longitude": 0.70210599999999
              },
              "endpoint": "/api/v1/countries/16/cities"
            },
            {
              "id": 17,
              "type": "countries",
              "name": "Lithuania",
              "images": [
                "http://loremflickr.com/1000/1000/lithuania,landmark/all"
              ],
              "location": {
                "latitude": -7.245977,
                "longitude": 21.411105
              },
              "endpoint": "/api/v1/countries/17/cities"
            },
            {
              "id": 18,
              "type": "countries",
              "name": "Luxembourg",
              "images": [
                "http://loremflickr.com/1000/1000/luxembourg,landmark/all"
              ],
              "location": {
                "latitude": 63.376938,
                "longitude": 100.750017
              },
              "endpoint": "/api/v1/countries/18/cities"
            },
            {
              "id": 19,
              "type": "countries",
              "name": "Malta",
              "images": [
                "http://loremflickr.com/1000/1000/malta,landmark/all"
              ],
              "location": {
                "latitude": 87.108971,
                "longitude": -142.270847
              },
              "endpoint": "/api/v1/countries/19/cities"
            },
            {
              "id": 20,
              "type": "countries",
              "name": "Netherlands",
              "images": [
                "http://loremflickr.com/1000/1000/netherlands,landmark/all"
              ],
              "location": {
                "latitude": -39.176207,
                "longitude": 84.936477
              },
              "endpoint": "/api/v1/countries/20/cities"
            }
          ],
          "meta": {
            "pagination": {
              "total": 28,
              "count": 20,
              "per_page": 20,
              "current_page": 1,
              "total_pages": 2,
              "links": {
                "next": "/api/v1/continents/1/countries?page=2"
              }
            }
          }
        }
        


#### Display cities in country [GET /countries/{country}/cities]

+ Parameters 
    + country:4
    
+ Request (application/json)
+ Response 200 (application/json)

        {
          "data": [
            {
              "id": 1,
              "type": "cities",
              "name": "Bangkok",
              "images": [
                "http://loremflickr.com/1000/1000/bangkok/all"
              ],
              "location": {
                "latitude": -28.783158,
                "longitude": 93.934667
              },
              "endpoint": "/api/v1/cities/1"
            },
            {
              "id": 2,
              "type": "cities",
              "name": "Nonthaburi",
              "images": [
                "http://loremflickr.com/1000/1000/nonthaburi/all"
              ],
              "location": {
                "latitude": 27.141406,
                "longitude": 38.70659
              },
              "endpoint": "/api/v1/cities/2"
            },
            {
              "id": 3,
              "type": "cities",
              "name": "Nakhon Ratchasima",
              "images": [
                "http://loremflickr.com/1000/1000/nakhon%20ratchasima/all"
              ],
              "location": {
                "latitude": 42.200942,
                "longitude": 153.367495
              },
              "endpoint": "/api/v1/cities/3"
            },
            {
              "id": 4,
              "type": "cities",
              "name": "Chiang Mai",
              "images": [
                "http://loremflickr.com/1000/1000/chiang%20mai/all"
              ],
              "location": {
                "latitude": -24.724471,
                "longitude": 52.077748
              },
              "endpoint": "/api/v1/cities/4"
            },
            {
              "id": 5,
              "type": "cities",
              "name": "Hat Yai",
              "images": [
                "http://loremflickr.com/1000/1000/hat%20yai/all"
              ],
              "location": {
                "latitude": -22.25937,
                "longitude": -172.734359
              },
              "endpoint": "/api/v1/cities/5"
            },
            {
              "id": 6,
              "type": "cities",
              "name": "Udon Thani",
              "images": [
                "http://loremflickr.com/1000/1000/udon%20thani/all"
              ],
              "location": {
                "latitude": -85.711041,
                "longitude": -29.086084
              },
              "endpoint": "/api/v1/cities/6"
            },
            {
              "id": 7,
              "type": "cities",
              "name": "Pak Kret",
              "images": [
                "http://loremflickr.com/1000/1000/pak%20kret/all"
              ],
              "location": {
                "latitude": -40.133869,
                "longitude": 38.787225
              },
              "endpoint": "/api/v1/cities/7"
            },
            {
              "id": 8,
              "type": "cities",
              "name": "Khon Kaen",
              "images": [
                "http://loremflickr.com/1000/1000/khon%20kaen/all"
              ],
              "location": {
                "latitude": 15.784941,
                "longitude": 53.910232
              },
              "endpoint": "/api/v1/cities/8"
            },
            {
              "id": 9,
              "type": "cities",
              "name": "Chaophraya Surasak",
              "images": [
                "http://loremflickr.com/1000/1000/chaophraya%20surasak/all"
              ],
              "location": {
                "latitude": -79.027831,
                "longitude": 80.962387
              },
              "endpoint": "/api/v1/cities/9"
            },
            {
              "id": 10,
              "type": "cities",
              "name": "Ubon Ratchathani",
              "images": [
                "http://loremflickr.com/1000/1000/ubon%20ratchathani/all"
              ],
              "location": {
                "latitude": 57.985158,
                "longitude": -41.076543
              },
              "endpoint": "/api/v1/cities/10"
            },
            {
              "id": 11,
              "type": "cities",
              "name": "Nakhon Si",
              "images": [
                "http://loremflickr.com/1000/1000/nakhon%20si/all"
              ],
              "location": {
                "latitude": -47.485742,
                "longitude": 49.635404
              },
              "endpoint": "/api/v1/cities/11"
            },
            {
              "id": 12,
              "type": "cities",
              "name": "Nakhon Sawan",
              "images": [
                "http://loremflickr.com/1000/1000/nakhon%20sawan/all"
              ],
              "location": {
                "latitude": 39.040502,
                "longitude": -132.355167
              },
              "endpoint": "/api/v1/cities/12"
            },
            {
              "id": 13,
              "type": "cities",
              "name": "Nakhon Pathom",
              "images": [
                "http://loremflickr.com/1000/1000/nakhon%20pathom/all"
              ],
              "location": {
                "latitude": 21.388041,
                "longitude": -86.476997
              },
              "endpoint": "/api/v1/cities/13"
            },
            {
              "id": 14,
              "type": "cities",
              "name": "Phitsanulok",
              "images": [
                "http://loremflickr.com/1000/1000/phitsanulok/all"
              ],
              "location": {
                "latitude": -25.835869,
                "longitude": -32.362984
              },
              "endpoint": "/api/v1/cities/14"
            },
            {
              "id": 15,
              "type": "cities",
              "name": "Pattaya",
              "images": [
                "http://loremflickr.com/1000/1000/pattaya/all"
              ],
              "location": {
                "latitude": 59.072351,
                "longitude": -48.952759
              },
              "endpoint": "/api/v1/cities/15"
            },
            {
              "id": 16,
              "type": "cities",
              "name": "Songkhla",
              "images": [
                "http://loremflickr.com/1000/1000/songkhla/all"
              ],
              "location": {
                "latitude": -15.724846,
                "longitude": 31.327401
              },
              "endpoint": "/api/v1/cities/16"
            },
            {
              "id": 17,
              "type": "cities",
              "name": "Surat Thani",
              "images": [
                "http://loremflickr.com/1000/1000/surat%20thani/all"
              ],
              "location": {
                "latitude": -62.95442,
                "longitude": 153.361747
              },
              "endpoint": "/api/v1/cities/17"
            },
            {
              "id": 18,
              "type": "cities",
              "name": "Rangsit",
              "images": [
                "http://loremflickr.com/1000/1000/rangsit/all"
              ],
              "location": {
                "latitude": -69.038688,
                "longitude": -23.151541
              },
              "endpoint": "/api/v1/cities/18"
            },
            {
              "id": 19,
              "type": "cities",
              "name": "Yala",
              "images": [
                "http://loremflickr.com/1000/1000/yala/all"
              ],
              "location": {
                "latitude": -80.542335,
                "longitude": -165.771632
              },
              "endpoint": "/api/v1/cities/19"
            },
            {
              "id": 20,
              "type": "cities",
              "name": "Phuket",
              "images": [
                "http://loremflickr.com/1000/1000/phuket/all"
              ],
              "location": {
                "latitude": 37.710823,
                "longitude": 73.093144
              },
              "endpoint": "/api/v1/cities/20"
            }
          ],
          "meta": {
            "pagination": {
              "total": 30,
              "count": 20,
              "per_page": 20,
              "current_page": 1,
              "total_pages": 2,
              "links": {
                "next": "/api/v1/countries/2/cities?page=2"
              }
            }
          }
        }
        
        
## Group Images or videos posting

### Posts [/posts]
- PNPD-35 Assign location for share photo [Content Sharing]
- PNPD-36 Post content with comment activity and location [Content Sharing]

#### Retrieves post from id [GET]
+ Request follow a activity with success (application/json)
+ Response 200 (application/json)

#### Creates a new post [POST]
+ Request follow a activity with success (application/json)
+ Response 200 (application/json)

#### Updates post [PUT]
+ Request follow a activity with success (application/json)
+ Response 200 (application/json)

#### Delete post [DELETE]
+ Request follow a activity with success (application/json)
+ Response 200 (application/json)

### User posts [/user/{id}/posts]

#### Retrieves list of user's posts [GET]
+ Request follow a activity with success (application/json)
+ Response 200 (application/json)