FORMAT: 1A
HOST: http://pnpd.uat.maqe.com/api/v1

# PNPD API

### Sprint 1
- PNPD-14,Log in with e-mail [User]
- PNPD-13,Log in with Facebook [User]
- PNPD-12,Signup with e-mail [User]
- PNPD-10,Signup with Facebook [User]
- PNPD-16,Send e-mail link to reset password [User]
- PNPD-60,Display activities in customize activity,[Customize My Painai]
- PNPD-65,Follow activities,[Customize My Painai]
- PNPD-63,Display continents in customize places,[Customize My Painai]
- PNPD-59,Display places by the continent,[Customize My Painai]
- PNPD-21,Filter Painai page [Feed]
- PNPD-72,Display continent in Explore page [Explore]

## Group API Authentication and User login API
- PNPD-13,Log in with Facebook
- PNPD-14,Log in with e-mail

http://docs.pnpdauthen.apiary.io

## Group Signup

#### Signup with e-mail [POST /signup]
- PNPD-12,Signup with e-mail

+ Request (application/json)

        {
            "email":"test@gmail.com"
        }
        
+ Response 200 (application/json)

#### Signup with Facebook [POST /signup-facebook]
- PNPD-10,Signup with Facebook
+ Request with success (application/json)

        {
            "token_facebook":"xxxxxxxxxxxx"
        }

+ Response 200 (application/json)

        {
            "messages":["Success"]
        }
        
## Group Reset password
#### Send link to e-mail [POST /reset_password]
- PNPD-16,Send e-mail link to reset password
+ Request with success (application/json)

        {
            "email":"test@gmail.com"
        }


+ Response 200 (application/json)

        {
            "messages":["Success"]
        }
        
+ Request with error (application/json)

        {
            "email":"invalid@gmail.com"
        }

+ Response 501 (application/json)

        {
            "errors":["That email address is not valid. Please check it and try again"]
        }

## Group User Info
#### Current user [GET /me]

+ Request (application/json)
+ Response 200 (application/json)


        {"id":1,"email":"test@gmail.com","created_at":null,"updated_at":null}

## Group Customize My Painai
- PNPD-65, Follow activities
- PNPD-63, Display continents in customize places
- PNPD-59, Display places by the continent

### Follow [/follow]

#### Follow a activity or continent [POST]
+ Request follow a activity with success (application/json)

        {
            "type": "activities",
            "name: "PAI EAT"
        }
        
+ Response 200 (application/json)

        {
            "messages":["Success"]
        }

+ Request Follow a continent with success (application/json)

        {
            "type": "continents",
            "name: "EUROPE"
        }
        
+ Response 200 (application/json)

        {
            "messages":["Success"]
        }

### Activities [/activities]

#### List all activities [GET]

+ Request (application/json)
+ Response 200 (application/json)

        [
          {
            "type": "activities",
            "name": "PAI EAT",
            "images": [
              "http://lorempixel.com/1000/1000/city/?21878"
            ],
            "endpoint": "/api/v1/activities/pai%20eat"
          },
          {
            "type": "activities",
            "name": "PAI DRINK",
            "images": [
              "http://lorempixel.com/1000/1000/city/?95376"
            ],
            "endpoint": "/api/v1/activities/pai%20drink"
          },
          {
            "type": "activities",
            "name": "PAI SHOP",
            "images": [
              "http://lorempixel.com/1000/1000/city/?21878"
            ],
            "endpoint": "/api/v1/activities/pai%20shop"
          },
          {
            "type": "activities",
            "name": "PAI SLEEP",
            "images": [
              "http://lorempixel.com/1000/1000/city/?95376"
            ],
            "endpoint": "/api/v1/activities/pai%20sleep"
          },
          {
            "type": "activities",
            "name": "PAI CHECK-IN",
            "images": [
              "http://lorempixel.com/1000/1000/city/?21878"
            ],
            "endpoint": "/api/v1/activities/pai%20check-in"
          },
          {
            "type": "activities",
            "name": "PAI ADVENTURE",
            "images": [
              "http://lorempixel.com/1000/1000/city/?95376"
            ],
            "endpoint": "/api/v1/activities/pai%20adventure"
          },
          {
            "type": "activities",
            "name": "PAI NATURE",
            "images": [
              "http://lorempixel.com/1000/1000/city/?95376"
            ],
            "endpoint": "/api/v1/activities/pai%20nature"
          },
          {
            "type": "activities",
            "name": "PAI SPORT",
            "images": [
              "http://lorempixel.com/1000/1000/city/?95376"
            ],
            "endpoint": "/api/v1/activities/pai%20sport"
          }
        ]

#### Follow activities [POST]
+ Request (application/json)
+ Response 200 (application/json)


### Places [/places]

#### Display customize places [GET]
+ Request (application/json)
+ Response 200 (application/json)

        [
          {
            "type": "continents",
            "name": "EUROPE",
            "images": [
              "http://lorempixel.com/1000/1000/city/?21878"
            ],
            "location": {
              "latitude": -23.291851,
              "longitude": -64.997873
            },
            "endpoint": "/api/v1/continents/europe/countries"
          },
          {
            "type": "continents",
            "name": "AFFRICA",
            "images": [
              "http://lorempixel.com/1000/1000/city/?22957"
            ],
            "location": {
              "latitude": 61.614921,
              "longitude": -158.650129
            },
            "endpoint": "/api/v1/continents/affrica/countries"
          },
          {
            "type": "continents",
            "name": "NORTH AMERICA",
            "images": [
              "http://lorempixel.com/1000/1000/city/?65627"
            ],
            "location": {
              "latitude": -4.423087,
              "longitude": 134.769223
            },
            "endpoint": "/api/v1/continents/north america/countries"
          },
          {
            "type": "countries",
            "name": "THAILAND",
            "images": [
              "http://lorempixel.com/1000/1000/city/?85691"
            ],
            "location": {
              "latitude": 59.600294,
              "longitude": -116.591653
            },
            "endpoint": "/api/v1/countries/thailand"
          },
          {
            "type": "continents",
            "name": "ASIA",
            "images": [
              "http://lorempixel.com/1000/1000/city/?95376"
            ],
            "location": {
              "latitude": 14.583206,
              "longitude": -165.701544
            },
            "endpoint": "/api/v1/continents/asia/countries"
          },
          {
            "type": "continents",
            "name": "SOUTH AMERICA",
            "images": [
              "http://lorempixel.com/1000/1000/city/?49173"
            ],
            "location": {
              "latitude": -60.391679,
              "longitude": 57.029127
            },
            "endpoint": "/api/v1/continents/south america/countries"
          },
          {
            "type": "countries",
            "name": "AUSTRALIA",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/australia"
          },
          {
            "type": "continents",
            "name": "ANTACTICA",
            "images": [
              "http://lorempixel.com/1000/1000/city/?68187"
            ],
            "location": {
              "latitude": 32.70329,
              "longitude": -83.885659
            },
            "endpoint": "/api/v1/continents/antactica/countries"
          }
        ]
        

#### Display countries by the continent [GET /continents/{continent}/countries]

+ Parameters 
    + continent:europe (string)
    
+ Request (application/json)
+ Response 200 (application/json)

        [
          {
            "type": "countries",
            "name": "United Kingdom",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/united kingdom"
          },
          {
            "type": "countries",
            "name": "France",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/france"
          },
          {
            "type": "countries",
            "name": "Finland",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/finland"
          },
          {
            "type": "countries",
            "name": "Belgium",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/belgium"
          },
          {
            "type": "countries",
            "name": "Latvia",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/latvia"
          },
          {
            "type": "countries",
            "name": "Denmark",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/denmark"
          },
          {
            "type": "countries",
            "name": "Norway",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/norway"
          },
          {
            "type": "countries",
            "name": "Bulgaria",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/bulgaria"
          },
          {
            "type": "countries",
            "name": "Hungary",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/hungary"
          },
          {
            "type": "countries",
            "name": "Italy",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/italy"
          },
          {
            "type": "countries",
            "name": "Netherlands",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/netherlands"
          },
          {
            "type": "countries",
            "name": "Portugal",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/portugal"
          },
          {
            "type": "countries",
            "name": "Romania",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/romania"
          },
          {
            "type": "countries",
            "name": "Greece",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/greece"
          },
          {
            "type": "countries",
            "name": "Austria",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/austria"
          },
          {
            "type": "countries",
            "name": "Spain",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/spain"
          },
          {
            "type": "countries",
            "name": "Sweden",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/sweden"
          },
          {
            "type": "countries",
            "name": "Germany",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/germany"
          },
          {
            "type": "countries",
            "name": "Switzerland",
            "images": [
              "http://lorempixel.com/1000/1000/city/?84556"
            ],
            "location": {
              "latitude": 47.215102,
              "longitude": 141.045943
            },
            "endpoint": "/api/v1/countries/switzerland"
          }
        ]